# Generated by Django 5.2.1 on 2025-12-27 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Production', 'Production'), ('IT', 'IT'), ('Facility', 'Facility'), ('Transport', 'Transport'), ('Other', 'Other')], max_length=50)),
                ('department', models.CharField(help_text='e.g. Production, Admin, HR', max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('is_scrapped', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, help_text='The employee primarily using this equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maintenance_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='core.maintenanceteam')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='core.maintenanceteam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('Corrective', 'Corrective (Breakdown)'), ('Preventive', 'Preventive (Routine Checkup)')], default='Corrective', max_length=20)),
                ('stage', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Repaired', 'Repaired'), ('Scrap', 'Scrap')], default='New', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, help_text='Required for Preventive Maintenance', null=True)),
                ('duration', models.FloatField(default=0.0, help_text='Hours spent on repair')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.equipment')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='core.technician')),
            ],
        ),
    ]
