# Generated by Django 5.2.1 on 2025-12-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='health',
            field=models.IntegerField(default=100, help_text='Equipment health percentage (0-100)'),
        ),
    ]
