# Generated by Django 5.2.1 on 2025-12-27 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipment_health'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('efficiency', models.FloatField(default=100.0, help_text='Efficiency percentage')),
                ('oee_target', models.FloatField(default=85.0, help_text='OEE Target percentage')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='scrap_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.maintenanceteam'),
        ),
        migrations.AddField(
            model_name='maintenanceteam',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='maintenance_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='department',
            field=models.CharField(help_text='Usage Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Hours spent'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.equipment'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='stage',
            field=models.CharField(choices=[('New', 'New Request'), ('In Progress', 'In Progress'), ('Repaired', 'Repaired'), ('Scrap', 'Scrap')], default='New', max_length=20),
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='core.equipmentcategory'),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.maintenancerequest')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='core.workcenter'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.workcenter'),
        ),
    ]
